name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js (if you're using Node.js)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust this if necessary

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Or whatever command you use to build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}  # Use the secret here
          publish_branch: gh-pages
          publish_dir: ./public  # Adjust this based on where your built files are
          allow_empty_commit: false
          force_orphan: false
          enable_jekyll: false
          disable_nojekyll: false
          exclude_assets: .github
