name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}  # This ensures the token is retrieved from GitHub secrets
          publish_branch: gh-pages    # The branch where the site will be hosted
          publish_dir: .             # Publish the root directory
          allow_empty_commit: false  # Ensure no empty commits are allowed
          force_orphan: false        # Create a new orphan branch for GitHub Pages
          enable_jekyll: false       # Disable Jekyll processing (if you don't need it)
